### PR TITLE
Further work on jaddison's patch

### PR DESCRIPTION
**Pull request by jaylett**
This introduces a way of getting the GraphAPI object fairly painlessly from the Facebook object (relies on James' fork of the pythonforfacebook facebook-sdk).

It also stops putting a pointless Facebook object on request.facebook; if there's no extractable Facebook cookie, don't put anything there. (An alternative would be to set it to `None`.)

### CODE REVIEW

**Comment by jaddison** [comment]
@jaylett - my only comment on this would be that it might be a good idea to locally cache the access_token from facebook.get_user_access_token() to prevent inefficient subsequent hits on the FB oauth endpoint.

**Comment by jaylett** [comment]
Sure, absolutely; I was being lazy to get our code working live :-)

**Comment by jaddison** [comment]
@jaylett - I have updated my fork as I described: If that works for you, feel free to close your pull request.  ;)

https://github.com/flashingpumpkin/django-socialregistration/pull/107

**Comment by jaylett** [comment]
Looks good, but I won't be able to test it for a while.

**Pull request merged**
