### PR TITLE
Creation of inactive users

### PR DESCRIPTION
**Pull request by lizrice**
Hello, 

This is a little change to allow social-registration to redirect to LOGIN_REDIRECT_INACTIVE_URL (rather than throwing an error) when a user is created or signed in through social-registration, but is inactive.  Useful if you're limiting the number of users, for example in a limited beta trial.  

Also a couple of extra notes in the docs - hopefully will save someone else a few minutes of research in the future. 

HTH!
Liz

### CODE REVIEW

**Comment by flashingpumpkin** [comment]
Hi, thanks!

The doc changes make sense. 

Do you mind adding a simple test case for `LOGIN_REDIRECT_INACTIVE_URL`?

**Comment by lizrice** [comment]
I'd be happy to - but I'm struggling to figure out how to do it!  I'll plug away a bit longer to see if I can figure it out, but meanwhile, if you have any pointers to a similar test that I could plagiarise for this purpose, do let me know.

**Comment by lizrice** [comment]
Some progress: here's a test case that checks that you get the 'standard' inactive response if your user gets created as inactive and you don't have LOGIN_REDIRECT_INACTIVE_URL set. 

The thing I don't know how to do is how to manipulate settings within the unit test environment, to run a test that checks that you get redirected to the right place if you do change that setting.  (FWIW, I can't see a similar test for the active user case for when LOGIN_REDIRECT_URL is set, so maybe that is OK).  

As you can probably tell, I'm pretty new to this Django unit testing malarky :-)

**Comment by flashingpumpkin** [comment]
Thanks :)

The thing with adjusting settings: It should be done in `.setUp` and then undone again in `.tearDown`. The problem here is that it would alter the settings for all test cases. 

I've added a workaround in c37e4c9d9d2863dfc4d7ac363b93bb28f9c1ee1a.

**Pull request merged**
