### PR TITLE
Support for LinkedIn via OAuth

### PR DESCRIPTION
**Pull request by theju**
There is support for OAuth and LinkedIn can be added very easily but I didn't want to repeat myself constantly and hence wish to have this part of django-socialregistration.

The settings attribute required for this are:
LINKEDIN_CONSUMER_KEY = ''
LINKEDIN_CONSUMER_SECRET_KEY = ''
LINKEDIN_REQUEST_TOKEN_URL = 'https://api.linkedin.com/uas/oauth/requestToken'
LINKEDIN_ACCESS_TOKEN_URL = 'https://api.linkedin.com/uas/oauth/accessToken'
LINKEDIN_AUTHORIZATION_URL = 'https://api.linkedin.com/uas/oauth/authenticate'

### CODE REVIEW

**Comment by flashingpumpkin** [comment]
Yay, sweet. Thanks a lot. Will have to try this out next week :)

**Comment by flashingpumpkin** [comment]
(I'll also version bump and upload it to PyPI)

**Comment by theju** [comment]
Did you get a chance to bump the version and upload it to PyPI?

**Comment by flashingpumpkin** [comment]
Updating later today. I'd like to test it out first and didn't get around to do it yet

**Comment by flashingpumpkin** [comment]
Finally, it's online. :) Sorry for the delay...

**Comment by theju** [comment]
Thank you. This saves so much of patching pain.

**Pull request merged**
