### PR TITLE
Facebook request permissions in settings file.

### PR DESCRIPTION
**Pull request by avanheuvelen**
Hi,

I've updated the project to have the request permissions for facebook in the settings file. Thought you might want to pull it.

Regards,

### CODE REVIEW

**Comment by avanheuvelen** [comment]
Sorry about the multitude of commits. I'm new to github.

**Comment by flashingpumpkin** [comment]
:)

I'll have a look after the weekend. Gotta find out why it's buggy with a memcache session backend.

**Comment by flashingpumpkin** [comment]
Cool. Added it. Thanks! 

Also, if you are running off some linux flavour, you can install `pandoc` which cross generates documents from one markup language into the other. 

`pandoc README.md -t rst > README.rst`

**Comment by avanheuvelen** [comment]
Cool, thanks! I'll install that.

**Pull request merged**
