### PR TITLE
fb and openid button tags improved

### PR DESCRIPTION
**Pull request by zalmoxis**
Fb and Oid tags can take an arbitrary number of strings and string variables that get concatenated to generate the url to the button image. This was needed in order to not hard-code the static/media urls.

### CODE REVIEW

**Comment by flashingpumpkin** [comment]
Thanks :)

**Comment by flashingpumpkin** [comment]
Oh. I just noticed that this breaks on Django 1.3. I'm reverting the merge... 

``` python
(django-socialregistration)alen@granite:[~/projects/django-socialregistration master-!+ 1 ↵]
$ tox -e py2.7-django1.4,py2.7-django1.3 
GLOB sdist-make: /home/alen/projects/django-socialregistration/setup.py
py2.7-django1.4 sdist-reinst: /home/alen/projects/django-socialregistration/.tox/dist/django-socialregistration-0.5.8.zip
py2.7-django1.4 runtests: commands[0]
py2.7-django1.4 runtests: commands[1]
Creating test database for alias 'default'...
..........................................................................................................
----------------------------------------------------------------------
Ran 106 tests in 8.510s

OK
Destroying test database for alias 'default'...
py2.7-django1.3 sdist-reinst: /home/alen/projects/django-socialregistration/.tox/dist/django-socialregistration-0.5.8.zip
py2.7-django1.3 runtests: commands[0]
py2.7-django1.3 runtests: commands[1]
Creating test database for alias 'default'...
...............................................................................E..........................
======================================================================
ERROR: test_tag_renders_correctly (socialregistration.contrib.openid.tests.TestTemplateTag)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/alen/projects/django-socialregistration/socialregistration/contrib/openid/tests.py", line 14, in test_tag_renders_correctly
    self.assertTrue('https://www.google.com/accounts/o8/id' in template.Template(tpl).render(template.Context({'request': None})))
  File "/home/alen/projects/django-socialregistration/.tox/py2.7-django1.3/local/lib/python2.7/site-packages/django/template/base.py", line 108, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/alen/projects/django-socialregistration/.tox/py2.7-django1.3/local/lib/python2.7/site-packages/django/template/base.py", line 136, in compile_string
    return parser.parse()
  File "/home/alen/projects/django-socialregistration/.tox/py2.7-django1.3/local/lib/python2.7/site-packages/django/template/base.py", line 239, in parse
    compiled_result = compile_func(self, token)
  File "/home/alen/projects/django-socialregistration/.tox/py2.7-django1.3/local/lib/python2.7/site-packages/django/utils/functional.py", line 55, in _curried
    return _curried_func(*(args+moreargs), **dict(kwargs, **morekwargs))
  File "/home/alen/projects/django-socialregistration/.tox/py2.7-django1.3/local/lib/python2.7/site-packages/django/template/base.py", line 810, in generic_tag_compiler
    raise TemplateSyntaxError(message)
TemplateSyntaxError: openid_form takes between 0 and 1 arguments

----------------------------------------------------------------------
Ran 106 tests in 1.233s

FAILED (errors=1)
Destroying test database for alias 'default'...
ERROR: InvocationError: '/home/alen/projects/django-socialregistration/tests/test.sh'
_____________________________________________________________________________________ summary _____________________________________________________________________________________
  py2.7-django1.4: commands succeeded
ERROR:   py2.7-django1.3: commands failed

```

I'll commit the `tox` runner once I went through all the issues on here.

**Comment by flashingpumpkin** [comment]
I'll see if I've got any time to fix it once I'm through here to merge it back in. Else I'm happy to merge if you can fix it :)

**Comment by zalmoxis** [comment]
It looks like the test needs to be updated to permit more parameters for openid form tag. I am not familiar with tox and didn't know how to run the tests. Now I am able to run the tests (thanks to the ease of tox and your error excerpt :) ). I will commit the fix and re-create the pull request.

**Pull request merged**
