### PR TITLE
I've fixed a bug which prevents django-socialregistration from working with Facebook

### PR DESCRIPTION
**Pull request by aidanlister**
See line 189 of:
https://github.com/facebook/python-sdk/blob/master/src/facebook.py

You've used API_KEY instead of APP_ID

Cheers for the module!

### CODE REVIEW

**Comment by thrashaholic** [comment]
This is incorrect. It should be API_KEY, and not APP_ID, according to the cookie that is being set by facebook. ( "fbs_" + API_KEY )

**Comment by aidanlister** [comment]
You're wrong ... just look at the source code in the link I provided:
    cookie = cookies.get("fbs_" + app_id, "")

**Comment by thrashaholic** [comment]
I suspect the sdk source is incorrect. Look at the cookie being set by facebook, not the wrongly named variable in the python sdk. ( Or you know, see what actually works, because it isn't app_id... )

**Comment by aidanlister** [comment]
I think maybe you have confused the app id with the api key... this is the cookie I see from my site:
    'fbs_137438592971812': 'access_token=137438592971812...'

Given there's many thousands of people using the python sdk and no issue in the queue saying "documentation, examples and source code for facebook python sdk are wrong", I think the balance of probabilities does suggest that you are incorrect.

**Comment by thrashaholic** [comment]
Strange. This is the cookie I see: fbs_50e2f6d6717a0a05df29ece01d4d2426. ( Looks like an API_KEY to me, not an APP_ID...right? ) I've been using this library for about 4 months now and it has always worked before with API_KEY, and does not work for me using APP_ID.

**Comment by aidanlister** [comment]
Well it doesn't surprise me that facebook is doing weird shit. I have no idea how this should be handled if facebook sends one or the other arbitrarily.

**Comment by thrashaholic** [comment]
Figured it out. It is supposed to be APP_ID as all the documentation suggests. However, Facebook sets the cookie name based on what you pass in to the FB.init javascript function, and this library is passing in API_KEY. So it needs to be changed in facebook_js.html and in middleware.py to be correct and functional. You must not be using the JS template tags, whereas I am - that would explain the difference.

**Comment by aidanlister** [comment]
Well diagnosed sir. I'm not using the template tags, I gave up on socialregistration and wrote django_facebook: https://github.com/aidanlister/django-facebook

I needed tighter integration and I didn't like having crazy uuid based usernames. Obviously this is no good if you're using twitter or oauth though :)

**Comment by flashingpumpkin** [comment]
Hm, I'll pull the changes in if someone goes to the lengths to change the middleware and facebook_js.html ... I'm currently not using socialregistration...

**Pull request closed without merging**
