### PR TITLE
Fixing an issue where 'next' is lost in a new user signup

### PR DESCRIPTION
**Pull request by jaddison**
Issue was found when creating a new user via Facebook Connect, the 'next' session variable gets lost when login() is called - Django is designed to do this.  This fix simply retrieves the value of 'next' before the call to login() and sets it back afterward.

### CODE REVIEW

**Comment by jaddison** [comment]
Pushed up changes too quickly.  Adding in a fix on my fix.

**Comment by flashingpumpkin** [comment]
Cool, thanks!

**Comment by flashingpumpkin** [comment]
I'll add a version bump too and push the new version to pypi on monday

**Comment by jaddison** [comment]
I'm sure you're busy, but any chance PyPi will be updated with 0.4.5 this week?  I'd much prefer to refer to a package than raw source if possible.  ;)  Cheers!

**Comment by flashingpumpkin** [comment]
Sorry, my bad. Uploaded it now.

**Pull request merged**
