### PR TITLE
Template Tags Conflict With Django Pagination

### PR DESCRIPTION
**Pull request by albertsun**
The template context variable 'next' conflicts with django pagination in generic views.
I've renamed it to next_page to avoid conflict.

I noticed that on pages where I was using a generic view with the paginate_by value set and also including the login buttons, clicking them would lead to pages like this.
http://127.0.0.1:8000/social/facebook/login/2

The buttons have a hidden form field with the context variable next. As it turns out, Django pagination also sets that variable with the number of the next page.

To reproduce this error, do something like this and put the facebook and twitter tags in the template.

```
from django.views.generic import list_detail
urlpatterns = patterns('',
    (r'^mymodel/(page/(?P<page>[0-9]+)/)?$', list_detail.object_list, { "queryset": MyModel.objects.all(), "paginate_by":20}),
)
```

### CODE REVIEW

**Comment by flashingpumpkin** [comment]
Hi

Using a `next` context variable / GET parameter is the canonical way to redirect users post login in Django, see these links:

https://code.djangoproject.com/browser/django/trunk/django/contrib/auth/__init__.py#L8
https://code.djangoproject.com/browser/django/trunk/django/contrib/admin/templates/admin/login.html#L39

I'm a bit reluctant to change it to `next_page`, but I'm happy to make it dependent on the `REDIRECT_FIELD_NAME` setting.

**Comment by albertsun** [comment]
That seems like a good solution

**Comment by flashingpumpkin** [comment]
Cool, send another pull request and add yourself to the AUTHORS file :)

**Comment by albertsun** [comment]
It doesn't look like REDIRECT_FIELD_NAME is a Django setting. Instead, in each of the views that need it, its a parameter that can be passed. I'm not sure how I would do that for a template tag here.

If this were to be a custom setting like SOCIALREGISTRATION_REDIRECT_FIELD_NAME or w/e with a default of "next" then the edit would be to:

Then in the template tags check for SOCIALREGISTRATION_REDIRECT_FIELD_NAME in context, and in the templates output SOCIALREGISTRATION_REDIRECT_FIELD_NAME as the hidden field's name, and in views.py's _get_next function use SOCIALREGISTRATION_REDIRECT_FIELD_NAME instead of next too.

Does that sound workable?

**Pull request closed without merging**
