### PR TITLE
Support offline_access facebook permission

### PR DESCRIPTION
**Pull request by jpic**
offline_access facebook permission allows to re-use a facebook authentication token any time.

This also enables socialregistration users to access request.facebook.graph even if the client facebook session expired.

The patch respects backward compatibility, which means that if your app already has offline_access permissions, then it should work out of the box.

The base testing protocol is: sign-in or sign-up to the django site via facebook which should save access_token in the FacebookProfile instance with this patch. Then logout from facebook, clear all cookies, and login to your django site via /admin. If your FacebookProfile has access_token right, then your django site should be able to use request.facebook.graph even though the browser is not logged in facebook.

What do you think ?

### CODE REVIEW

**Comment by flashingpumpkin** [comment]
Looking at it. Will add in some way. What's a little offsetting is a new database field, but it's obviously required.

Another way might be to introduce signals that fire after connecting. Users can then handle all the data they want.

**Comment by jaylett** [comment]
I'd say that the field belongs precisely where @jpic has put it, on the FacebookProfile. Having to add it elsewhere would feel odd IMHO.

**Comment by flashingpumpkin** [comment]
I've added the signals bit mentioned, and you're right. I'll merge the changes - unfortunately auto merge does not work.

**Comment by jpic** [comment]
Actually my repo also contains the same kind of modifications for twitter, if you're interrested feel free to take it.

We use it on http://playlistnow.fm

Cheers

**Pull request closed without merging**
