### PR TITLE
Fix for bug that connects multiple profiles to users in some instances.

### PR DESCRIPTION
**Pull request by wesc**
Here's the situation:
1. I log into Facebook as Alice
2. I log into the Django app using Facebook
3. I log out of Facebook
4. I log into Facebook as Bob
5. The app exposes a "connect with facebook" button, even though I'm logged in as Alice. I click on it.

The result: both Alice and Bob's Facebook profiles are linked with Alice's account in the app.

What this patch does is check to see if request.user does not match the user associated with the profile. If this is the case, log in as the user associated with the profile, rather than connect the profile with request.user.

### CODE REVIEW

**Comment by flashingpumpkin** [comment]
Makes sense. Could you add a testcase for this too?

**Comment by flashingpumpkin** [comment]
Ah well, looks like I'm doing some updates again so I might add the tests myself

**Comment by wesc** [comment]
I'm a bit occupied at the moment, but will hopefully be free to write the test after a week or so.

**Comment by wesc** [comment]
Just added another fix to this pull request.

(Forgive me, I'm not a real git or github user. I would have preferred to make a separate pull request for this commit, but apparently that's not how it works)

Steps:
1. User logs in, not via FB
2. User connects with FB
3. socialregistration connects the FB profile to the User, but does not re-authenticate or login.

This patch changes step 3 so that we re-authenticate and login. It might seem arbitrary, but the reason we should do this is because Django keeps track of which authentication backend a user authenticated with. I _think_ the right thing to do is to set the authentication backend in this case to be FB.

This commit solves a problem with my use case, which is mixing django-lazysignup with socialregistration.

**Pull request closed without merging**
