### PR TITLE
Fixed debug toolbar fail on setup page

### PR DESCRIPTION
**Pull request by muhuk**
`facebook_login` view initializes `FacebookProfile` but doesn't save it. Then `request_vars` fails because `FacebookProfile.__unicode__()` assumes `user` is set.

I have modified `__unicode__` to function properly.

Please pull.

### CODE REVIEW

**Comment by ghost** [comment]
This would be a nice addition. Thanks.

**Comment by ghost** [comment]
How exactly does this get pulled into the main branch? Why wouldn't it be?

**Comment by flashingpumpkin** [comment]
Hey. Cherry picked the change and pushed to master.

**Comment by flashingpumpkin** [comment]
_close_

**Comment by muhuk** [comment]
Thank you.

**Comment by dbrgn** [comment]
Same thing happens with Twitter and OpenID. See #71.

**Pull request closed without merging**
