### PR TITLE
Adding the request to the social_client (Facebook) obj

### PR DESCRIPTION
**Pull request by jaddison**
Adding 'request' to the social_client on connecting a Facebook profile to an existing user - matches the setup() view.  This allows signals to set user messages.

This happens in all other signup/signin cases with twitter and facebook, except in the case where hooking up FB to an existing user, it seems.

### CODE REVIEW

**Comment by jaddison** [comment]
To use the GraphAPI, one should look to use the code from (https://github.com/pythonforfacebook/facebook-sdk/pull/3) on the facebook-sdk module coupled with the updates in this django-socialregistration pull request.  Hopefully both will get merged soon - or some similar variation.

**Comment by jaylett** [comment]
Wouldn't it be better to provide request.facebook.graph using something like SimpleLazyObject, so client code doesn't have to change?

**Comment by jaylett** [comment]
Have investigated, and SimpleLazyObject would be an enormous pain for me without a lot of work to make it picklable. So instead I've just made it easier to grab a GraphAPI object: https://github.com/flashingpumpkin/django-socialregistration/pull/110.

**Comment by flashingpumpkin** [comment]
Looking into it now

**Comment by flashingpumpkin** [comment]
I'm thinking of getting rid of all the javascript bits (Re: deprecation in October) and adding the proper OAuth2 workflow instead. Only pain here is - there's currently no library that supports OAuth2 for Python. Or I didn't find it.

**Comment by flashingpumpkin** [comment]
Correction: I just found one on PyPI that wasn't around a couple of weeks ago. :)

**Comment by jaddison** [comment]
@flashingpumkin: Perhaps I'm misunderstanding you, but the javascript method of authentication isn't going away, it's just moving to OAuth2.0, like the in-Python method.  You don't need to 'replace' the JS method...

If you mean getting rid of all the OLD authentication code (the stuff that won't work after Oct 1st), then yes, I will agree with that.

Perhaps you can elaborate on what specifically needs to be done to bring django-socialregistration up to speed with the Oct 1 Facebook changes?  I feel like I'm misunderstanding things here a bit and don't want to add to any confusion.  ;)

**Comment by flashingpumpkin** [comment]
@jaddison Yes, I mean getting rid of old code that won't work after Oct 1st - I assumed wrongly that this includes the JavaScript parts too. Unfortunately I'm not quite up to speed currently. 

On another note though, I've always disliked the JavaScript login flow of Facebook. When it first came out, there was a lot of black magic with cross site (domain) requests happening - so I _would_ like to get rid of all the JavaScript bits and turn the login flow for Facebook to be purely on the server, like the current OAuth implementations for Twitter & LinkedIn and OpenID does it. It keeps me saner. :)

I reckon that shouldn't be intermingled with this code here though and happen on another branch (and version).

**Comment by jaddison** [comment]
@theju, @jaylett: See pull https://github.com/flashingpumpkin/django-socialregistration/pull/115 for some further updates related to your discussion.  They apparently didn't make it into this one before @flashingpumpkin merged it.

**Comment by theju** [comment]
@jaddison Shouldn't the requirements.txt also be updated in your pull request to reflect the new facebook-sdk? With that change, I can close my pull request. Let me know when you have updated the pull request.

**Pull request merged**
